[package]
name = "virus_document"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
bitflags.workspace = true
ropey.workspace = true
similar.workspace = true
smol_str.workspace = true
tempfile.workspace = true
tree-sitter-rust.workspace = true
tree-sitter.workspace = true
unicode-properties.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true
