[workspace]
resolver = "2"         # Important! wgpu needs this!
members = ["crates/*"]

[workspace.package]
authors = ["Romain TRUCHI"]
edition = "2021"

[workspace.dependencies]
pixels = "0.11"
winit = "0.27"
winit_input_helper = "0.13"
tiny-skia = "0.8"

[profile.dev]
debug = false
strip = true

[profile.dev.package."*"]
opt-level = 3
