[workspace]
resolver = "2"                     # Important! wgpu needs this!
members = ["crates/*"]
default-members = ["crates/virus"]

[workspace.package]
authors = ["Romain TRUCHI"]
edition = "2021"

[workspace.dependencies]
virus-editor = { path = "crates/editor", package = "editor" }
virus-graphics = { path = "crates/graphics", package = "graphics" }

lru = "0.9.0"
pixels = "0.11"
swash = "0.1.6"
winit = "0.27"
tree-sitter = "0.20"
tree-sitter-rust = "0.20"
ropey = "1.5"

[profile.dev]
debug = false
strip = true

[profile.dev.package."*"]
opt-level = 3
