[package]
name = "ui"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
ropey.workspace = true
swash.workspace = true
tween.workspace = true
virus-common.workspace = true
virus-editor.workspace = true
virus-graphics.workspace = true
winit.workspace = true
