[package]
name = "graphics"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
pixels.workspace = true
winit.workspace = true
winit_input_helper.workspace = true
tiny-skia.workspace = true
