[package]
name = "graphics"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
bytemuck.workspace = true
image.workspace = true
pollster.workspace = true
swash.workspace = true
virus-common.workspace = true
wgpu.workspace = true
winit.workspace = true
