[package]
name = "virus"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
virus-common.workspace = true
virus-editor.workspace = true
virus-ui.workspace = true
winit.workspace = true
