[package]
name = "virus"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
pixels.workspace = true
winit.workspace = true
skia.workspace = true

graphics = { path = "../graphics" }
