[package]
name = "virus"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
virus-graphics.workspace = true

pixels.workspace = true
winit.workspace = true
skia.workspace = true
