[package]
name = "virus"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
virus-common.workspace = true
virus-editor.workspace = true
virus-graphics.workspace = true

pixels.workspace = true
winit.workspace = true
