[package]
name = "editor"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
virus-common.workspace = true

tree-sitter.workspace = true
tree-sitter-rust.workspace = true
ropey.workspace = true
unicode-segmentation.workspace = true
